[global]

# We get a readable error without this.
developmentMode = false

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not run as a rerun script.
runOnSave = true

# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
displayEnabled = true

# Controls whether uncaught app exceptions are displayed in the browser. By default, this is set to True and Streamlit displays app exceptions and associated tracebacks in the browser.
showErrorDetails = true

[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all share the same secret.
cookieSecret = "a-random-key-here"

# If false, will attempt to open a browser window on start.
headless = true

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address where the server will listen for client and browser connections. Use this if you want to bind the server to a specific address. If set, the server will only be accessible from this address, and not from any other address.
address = "0.0.0.0"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = true

[browser]

# Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Port where users should point their browsers in order to connect to the app. This can differ from the port where the server is actually listening.
serverPort = 8501
